const menu = [
    {
      id: 1,
      title: 'Pancake',
      category: 'breakfast',
      price: 15.99,
      img: './img/item-1.jpeg',
      desc: 'The taste of milk is in buttermilk pancakes! Add flavor to your day with our strained pancakes with a soft texture.',
    },
    {
      id: 2,
      title: 'Diner Double Hamburger',
      category: 'lunch',
      price: 13.99,
      img: './img/item-2.jpeg',
      desc: 'Our double hamburger prepared diner style is the perfect choice for your lunch with its delicious taste and satisfying structure!',
    },
    {
      id: 3,
      title: 'Godzilla Milkshake',
      category: 'shakes',
      price: 6.99,
      img: './img/item-3.jpeg',
      desc: 'A legendary taste awaits you! Pamper yourself with our Godzilla Milkshake and take a sweet break.',
    },
    {
      id: 4,
      title: 'Village Taste',
      category: 'breakfast',
      price: 20.99,
      img: './img/item-4.jpeg',
      desc: 'The indispensable taste of village breakfasts is here now! The Village Taste breakfast, prepared with completely natural ingredients, invites you to a delicious feast of taste.',
    },
    {
      id: 5,
      title: 'Egg Bomb',
      category: 'lunch',
      price: 22.99,
      img: './img/item-5.jpeg',
      desc: 'The indispensable taste of village breakfasts is here now! The Village Taste breakfast, prepared with completely natural ingredients, invites you to a delicious feast of taste.',
    },
  
    {
      id: 6,
      title: 'Oreo Dream',
      category: 'shakes',
      price: 18.99,
      img: './img/item-6.jpeg',
      desc: 'Oreo sevenler için muhteşem bir lezzet! Oreo Hayali sizi tatlı bir dünyaya götürüyor. Lezzetine doyum olmaz!',
    },
    {
      id: 7,
      title: 'Bacon Seli',
      category: 'breakfast',
      price: 8.99,
      img: './img/item-7.jpeg',
      desc: 'For those who love bacon, a must for breakfast! Bacon Flood, prepared with plenty of freshly fried bacon and other flavors, will provide you with a great start to the day.',
    },
    {
      id: 8,
      title: 'American Classic',
      category: 'lunch',
      price: 12.99,
      img: './img/item-8.jpeg',
      desc: 'This lunch, prepared with the classic tastes of American cuisine, offers an experience that is not satisfying. Moreover, it is preferred for its affordable price!',
    },
    {
      id: 9,
      title: 'Quarantine Friend',
      category: 'shakes',
      price: 16.99,
      img: './img/item-9.jpeg',
      desc: 'A delicious milkshake that will not leave you alone when you are bored during quarantine days! Have a sweet getaway with Quarantine Buddy.',
    },
    {
      id: 10,
      title: 'Bison Steak',
      category: 'lunch',
      price: 22.99,
      img: './img/item-10.jpeg',
      desc: 'The unique taste of bison meat is combined with special spices and sauces. Bison Steak is the perfect choice for your dinner!',
    },
  ];
  
  export default menu;